
# Database configuration
database:
  # Driver details for the database
  driver: oracle.jdbc.OracleDriver
  # Database URL, username and password - change as required
  url: "jdbc:oracle:thin:@host.ebi.ac.uk:1531:spotpro"
  username: user
  password: password

# Storage configuration
storage:
  # Storage engine type(s) to use
  engineTypes: [ solr ]

  # Solr configuration (if solr in engineTypes)
  solr:
    # Base URL for the document index
    baseUrl: http://localhost:8983/solr/documents
    
    # Commit within time when storing items (in ms)
    commitWithinMs: 60000
    
  # Configuration for other search engines, as applicable
  other:
    elasticsearch:
      class: "uk.co.flax.biosolr.ontology.documents.storage.es.ESStorageEngine"
