
# Ontology config details
# URL of the Ontology SOLR endpoint
ontologySolrUrl: http://localhost:8983/solr/ontology
# URL of the document SOLR endpoint
documentsSolrUrl: http://localhost:8983/solr/documents

# URI for the ontology to reference against
ontologyUri: http://www.ebi.ac.uk/efo/efo.owl

# Database configuration
database:
  # Driver details for the database
  driver: oracle.jdbc.OracleDriver
  # Database URL, username and password - change as required
  url: "jdbc:oracle:thin:@host.ebi.ac.uk:1531:spotpro"
  username: user
  password: password

