
# Database configuration
database:
  # Driver details for the database
  driver: oracle.jdbc.OracleDriver
  # Database URL, username and password - change as required
  url: "jdbc:oracle:thin:@host.ebi.ac.uk:1531:spotpro"
  username: user
  password: password

# Storage configuration
storage:
  # Storage engine type(s) to use
  engineTypes: [ solr ]

  # Solr configuration (if solr in engineTypes)
  solr:
    # Base URL for the document index
    baseUrl: http://localhost:8983/solr/documents
    
    # Commit within time when storing items (in ms)
    commitWithinMs: 60000
    
  # Configuration for other search engines, as applicable
  other:
    elasticsearch:
      # The ES storage engine class
      class: "uk.co.flax.biosolr.ontology.documents.storage.elasticsearch.ESStorageEngine"
      
      # Additional configuration
      configuration:
        # Use the nodeClient (may have firewall issues)
        nodeClient: false
        
        # List of servers, to be used if *not* using nodeClient
        servers: 
          - localhost:9300
        
        # Name of the cluster - defaults to elasticsearch
        # clusterName: elasticsearch
        
        # Name of the index to use
        indexName: spot
        # Type of items being stored
        indexType: document
